import { BasicColumn } from '@/components/Table';

import dayjs from 'dayjs';

export function getBasicColumns(): BasicColumn[] {
  return [
    {
      title: 'Tên thiết bị',
      dataIndex: ['equipment', 'equipment_name'],
      align: 'left',
      fixed: 'left',
      width: 100,
    },
    {
      title: 'Mã số',
      dataIndex: 'equipment_id',
      align: 'left',
      fixed: 'left',
      width: 100,
    },
    {
      title: 'Đơn vị sử dụng',
      dataIndex: 'using_unit',
      align: 'left',
      fixed: 'left',
      width: 150,
    },
    {
      title: 'Ngày bảo dưỡng',
      dataIndex: 'maintenance_date',
      align: 'left',
      fixed: 'left',
      width: 140,
      customRender: ({ value }) => (value ? dayjs(value).format('DD/MM/YYYY') : ''),
    },
    {
      title: 'Đơn vị bảo dưỡng',
      dataIndex: 'maintenance_unit',
      align: 'left',
      width: 150,
    },
    {
      title: 'Người bảo dưỡng',
      dataIndex: 'user_id',
      align: 'left',
      width: 100,
    },
    {
      title: 'Ghi chú',
      dataIndex: 'note',
      align: 'left',
      width: 200,
    },
  ];
}

export function getActionColumn(): BasicColumn {
  return {
    width: 120,
    title: 'Thao tác',
    dataIndex: 'action',
  };
}

export function mockData(): any[] {
  return [
    {
      equipment_id: 'Máy 02',
      _id: 'MS1000',
      user_unit: 'Đơn vị 1',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1001',
      user_unit: 'Đơn vị 2',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1002',
      user_unit: 'Đơn vị 3',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1003',
      user_unit: 'Đơn vị 4',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1004',
      user_unit: 'Đơn vị 5',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1005',
      user_unit: 'Đơn vị 6',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1006',
      user_unit: 'Đơn vị 7',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1007',
      user_unit: 'Đơn vị 8',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1008',
      user_unit: 'Đơn vị 9',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1009',
      user_unit: 'Đơn vị 10',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1004',
      user_unit: 'Đơn vị 5',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1005',
      user_unit: 'Đơn vị 6',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1006',
      user_unit: 'Đơn vị 7',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1007',
      user_unit: 'Đơn vị 8',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1004',
      user_unit: 'Đơn vị 5',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1005',
      user_unit: 'Đơn vị 6',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1006',
      user_unit: 'Đơn vị 7',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1007',
      user_unit: 'Đơn vị 8',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1008',
      user_unit: 'Đơn vị 9',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1009',
      user_unit: 'Đơn vị 10',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1004',
      user_unit: 'Đơn vị 5',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1008',
      user_unit: 'Đơn vị 9',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1009',
      user_unit: 'Đơn vị 10',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1004',
      user_unit: 'Đơn vị 5',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1007',
      user_unit: 'Đơn vị 8',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1008',
      user_unit: 'Đơn vị 9',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1009',
      user_unit: 'Đơn vị 10',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1004',
      user_unit: 'Đơn vị 5',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1007',
      user_unit: 'Đơn vị 8',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1008',
      user_unit: 'Đơn vị 9',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1009',
      user_unit: 'Đơn vị 10',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
    {
      equipment_id: 'Máy 02',
      _id: 'MS1004',
      user_unit: 'Đơn vị 5',
      maintenance_date: '30/07/2024',
      maintenance_unit: 'Đơn vị bảo dưỡng',
      maintenance_technician: 'User',
      note: '-',
    },
  ];
}
