import { BasicColumn, FormProps } from '@/components/Table';
import { formatNumber } from '@/utils/helper/tsxHelper';
import { Checkbox, Progress } from 'ant-design-vue';
import dayjs from 'dayjs';

export function getBasicColumnsProductionPlan(): BasicColumn[] {
  return [
    {
      title: 'PO',
      dataIndex: 'production_order',
      align: 'center',
      fixed: 'left',
      width: 120,
      customRender: ({ value }) => value?.po_number,
    },
    {
      title: 'Mã khách hàng',
      dataIndex: 'customer_id',
      align: 'center',
      width: 150,
    },
    {
      title: 'Tên khách hàng',
      align: 'center',
      width: 150,
      customRender: ({ record }) => record?.customer?.customer_name,
    },
    {
      title: 'Dòng sản phẩm',
      align: 'center',
      width: 150,
      customRender: ({ record }) => record?.product?.product_category?.product_category_name,
    },
    {
      title: 'Mã sản phẩm',
      dataIndex: 'product_id',
      align: 'center',
      width: 150,
    },
    {
      title: 'Công đoạn',
      dataIndex: 'equipment',
      align: 'center',
      width: 100,
      customRender: ({ value }) => value?.process_id,
    },
    {
      title: 'Máy',
      dataIndex: 'equipment_id',
      align: 'center',
      width: 100,
    },
    {
      title: 'Mã thành phần',
      dataIndex: 'component_id',
      align: 'center',
      width: 150,
    },
    {
      title: 'Mã lô sản xuất',
      dataIndex: 'batch_code',
      align: 'center',
      width: 150,
    },
    {
      title: 'Tên sản phẩm',
      dataIndex: 'product_name',
      align: 'center',
      width: 150,
      customRender: ({ record }) => record?.product?.product_name,
    },
    {
      title: 'Số lượng đặt',
      dataIndex: 'quantity',
      align: 'right',
      width: 100,
      customRender: ({ value }) => formatNumber(value),
    },
    {
      title: 'Thời gian bắt đầu',
      dataIndex: 'start_time',
      align: 'center',
      width: 150,
      customRender: ({ value }) => (value ? dayjs(value).format('DD/MM/YYYY HH:mm') : ''),
    },
    {
      title: 'Thời gian kết thúc',
      dataIndex: 'end_time',
      align: 'center',
      width: 150,
      customRender: ({ value }) => (value ? dayjs(value).format('DD/MM/YYYY HH:mm') : ''),
    },
    {
      title: 'Ngày giao hàng',
      dataIndex: 'delivery_date',
      align: 'center',
      width: 150,
      customRender: ({ record }) => {
        // console.log('record', record);
        return record
          ? dayjs(record?.production_order?.delivery_date).format('DD/MM/YYYY HH:mm')
          : '';
      },
    },
  ];
}

export function getBasicColumns(): BasicColumn[] {
  return [
    {
      title: 'PO',
      dataIndex: 'po_number',
      align: 'center',
      fixed: 'left',
      width: 100,
    },
    {
      title: 'Mã sản phẩm',
      dataIndex: 'product_id',
      align: 'center',
      width: 150,
    },
    {
      title: 'Mã khách hàng',
      dataIndex: 'customer_id',
      align: 'center',
      width: 150,
    },
    // {
    //   title: 'Khách hàng',
    //   dataIndex: 'customer_id',
    //   align: 'center',
    //   width: 150,
    //   customRender: ({ record }) => record?.customer?.customer_name,
    // },
    // {
    //   title: 'Mã lô sản xuất',
    //   dataIndex: 'batch_code',
    //   align: 'center',
    //   width: 180,
    // },
    {
      title: 'Tên sản phẩm',
      dataIndex: 'product_name',
      align: 'center',
      width: 180,
      customRender: ({ record }) => record?.product?.product_name,
    },
    {
      title: 'Số lượng',
      dataIndex: 'quantity',
      align: 'right',
      width: 100,
      customRender: ({ value }) => formatNumber(value),
    },
    {
      title: 'Ngày nhận đơn',
      dataIndex: 'order_date',
      align: 'center',
      width: 150,
      customRender: ({ value }) => (value ? dayjs(value).format('DD/MM/YYYY') : ''),
    },
    {
      title: 'Ngày giao hàng',
      dataIndex: 'delivery_date',
      align: 'center',
      width: 150,
      customRender: ({ value }) => (value ? dayjs(value).format('DD/MM/YYYY') : ''),
    },
    {
      title: 'Ghi chú',
      dataIndex: 'note',
      align: 'center',
      width: 200,
    },
    // {
    //   title: 'Thời gian upload',
    //   dataIndex: 'created_at',
    //   align: 'center',
    //   width: 150,
    //   customRender: ({ value }) => (value ? dayjs(value).format('DD/MM/YYYY HH:mm') : ''),
    // },
  ];
}

export function getFormConfig(): Partial<FormProps> {
  return {
    layout: 'vertical',
    schemas: [
      {
        field: `date`,
        label: `Thời gian`,
        component: 'RangePicker',
      },
      {
        field: `batch_code`,
        label: `Lô sản xuất`,
        component: 'Input',
      },
      {
        field: `product_id`,
        label: `Mã sản phẩm`,
        component: 'Input',
      },
    ],
  };
}

export function getActionColumn(): BasicColumn {
  return {
    title: 'Thao tác',
    dataIndex: 'action',
    width: 80,
  };
}

// Bảng tiến độ thực hiện đơn hàng
export function getBasicColumnsProcess(): BasicColumn[] {
  return [
    {
      title: 'Thông tin đơn hàng',
      children: [
        {
          title: 'Mã khách hàng',
          dataIndex: 'customer_id',
          align: 'center',
          width: 120,
        },
        {
          title: 'Ngày',
          dataIndex: 'date',
          align: 'center',
          width: 120,
        },
        {
          title: 'Mã sản phẩm',
          dataIndex: 'product_id',
          align: 'center',
          width: 120,
        },
        {
          title: 'Tên sản phẩm',
          dataIndex: 'product_name',
          align: 'center',
          width: 120,
        },
        {
          title: 'ĐVT',
          dataIndex: 'unit_name',
          align: 'center',
          width: 60,
        },
        {
          title: 'Dự kiến giao',
          dataIndex: 'estimate_date',
          align: 'center',
          width: 120,
        },
        {
          title: 'Số lượng',
          dataIndex: 'quantity',
          align: 'center',
          width: 100,
          customRender: ({ value }) => formatNumber(value),
        },
      ],
    },
    {
      title: 'Tiến độ giao hàng',
      children: [
        {
          title: 'SL đã giao',
          dataIndex: 'delivery_quantity',
          align: 'center',
          width: 100,
          customRender: ({ value }) => formatNumber(value),
        },
        {
          title: 'SL còn phải giao',
          dataIndex: 'delivery_quantity',
          align: 'center',
          width: 140,
          customRender: ({ value }) => formatNumber(value),
        },
        {
          title: 'Tiến độ giao hàng',
          dataIndex: 'delivery_process',
          align: 'center',
          width: 150,
          customRender: ({ value }) => (
            <Progress
              status="active"
              percent={value}
              format={(percent) => <small>{percent}%</small>}
            />
          ),
        },
        {
          title: 'Ngày hoàn thành',
          dataIndex: 'complete_date',
          align: 'center',
          width: 120,
        },
        {
          title: 'Đã đóng',
          dataIndex: 'is_packaged',
          align: 'center',
          width: 60,
          customRender: ({ value }) => {
            if (value) return <Checkbox checked />;
            return <Checkbox />;
          },
        },
        {
          title: 'Trạng thái hạn',
          dataIndex: 'deline_status',
          align: 'center',
          width: 120,
        },
      ],
    },
    {
      title: 'Tình hình sản xuất',
      children: [
        {
          title: 'SL kế hoạch',
          dataIndex: 'plan_quantity',
          align: 'center',
          width: 100,
          customRender: ({ value }) => formatNumber(value),
        },
        {
          title: 'SL thực tế',
          dataIndex: 'actual_quantity',
          align: 'center',
          width: 100,
          customRender: ({ value }) => formatNumber(value),
        },
        {
          title: 'SL nhập kho',
          dataIndex: 'warehouse_import_quantity',
          align: 'center',
          width: 100,
          customRender: ({ value }) => formatNumber(value),
        },
        {
          title: 'SL chờ nhập kho',
          dataIndex: 'warehouse_import_wait_quantity',
          align: 'center',
          width: 120,
          customRender: ({ value }) => formatNumber(value),
        },
        {
          title: 'SL.NG IQC',
          dataIndex: 'iqc_ng_quantity',
          align: 'center',
          width: 120,
          customRender: ({ value }) => formatNumber(value),
        },
      ],
    },
  ];
}

export const mockDataProcess: any[] = [
  {
    customer_id: 'KH001',
    date: '2025-02-28',
    product_id: 'SP001',
    product_name: 'Sản phẩm A',
    unit_name: 'Cái',
    estimate_date: '2025-03-05',
    quantity: 1000,
    delivery_quantity: 500, // SL đã giao & SL còn phải giao (tính theo yêu cầu ban đầu)
    delivery_process: 50,
    complete_date: '2025-03-06',
    is_packaged: true,
    deline_status: 'Đúng hạn',
    plan_quantity: 1000,
    actual_quantity: 950,
    warehouse_import_quantity: 900,
    warehouse_import_wait_quantity: 50,
    iqc_ng_quantity: 5,
  },
  {
    customer_id: 'KH002',
    date: '2025-02-27',
    product_id: 'SP002',
    product_name: 'Sản phẩm B',
    unit_name: 'Bộ',
    estimate_date: '2025-03-10',
    quantity: 2000,
    delivery_quantity: 1200,
    delivery_process: 60,
    complete_date: '2025-03-11',
    is_packaged: false,
    deline_status: 'Trễ hạn',
    plan_quantity: 2000,
    actual_quantity: 1900,
    warehouse_import_quantity: 1850,
    warehouse_import_wait_quantity: 50,
    iqc_ng_quantity: 10,
  },
  {
    customer_id: 'KH003',
    date: '2025-02-25',
    product_id: 'SP003',
    product_name: 'Sản phẩm C',
    unit_name: 'Chiếc',
    estimate_date: '2025-03-02',
    quantity: 1500,
    delivery_quantity: 1500,
    delivery_process: 100,
    complete_date: '2025-03-02',
    is_packaged: true,
    deline_status: 'Đúng hạn',
    plan_quantity: 1500,
    actual_quantity: 1500,
    warehouse_import_quantity: 1500,
    warehouse_import_wait_quantity: 0,
    iqc_ng_quantity: 0,
  },
  {
    customer_id: 'KH004',
    date: '2025-03-01',
    product_id: 'SP004',
    product_name: 'Sản phẩm D',
    unit_name: 'Cái',
    estimate_date: '2025-03-08',
    quantity: 800,
    delivery_quantity: 300,
    delivery_process: 37.5,
    complete_date: '',
    is_packaged: false,
    deline_status: 'Đang giao hàng',
    plan_quantity: 800,
    actual_quantity: 600,
    warehouse_import_quantity: 500,
    warehouse_import_wait_quantity: 100,
    iqc_ng_quantity: 2,
  },
  {
    customer_id: 'KH005',
    date: '2025-03-02',
    product_id: 'SP005',
    product_name: 'Sản phẩm E',
    unit_name: 'Bộ',
    estimate_date: '2025-03-09',
    quantity: 500,
    delivery_quantity: 100,
    delivery_process: 20,
    complete_date: '',
    is_packaged: false,
    deline_status: 'Đang giao hàng',
    plan_quantity: 500,
    actual_quantity: 400,
    warehouse_import_quantity: 350,
    warehouse_import_wait_quantity: 50,
    iqc_ng_quantity: 1,
  },
  {
    customer_id: 'KH006',
    date: '2025-03-03',
    product_id: 'SP006',
    product_name: 'Sản phẩm F',
    unit_name: 'Cái',
    estimate_date: '2025-03-12',
    quantity: 1200,
    delivery_quantity: 600,
    delivery_process: 50,
    complete_date: '2025-03-12',
    is_packaged: true,
    deline_status: 'Đúng hạn',
    plan_quantity: 1200,
    actual_quantity: 1150,
    warehouse_import_quantity: 1100,
    warehouse_import_wait_quantity: 50,
    iqc_ng_quantity: 3,
  },
  {
    customer_id: 'KH007',
    date: '2025-03-04',
    product_id: 'SP007',
    product_name: 'Sản phẩm G',
    unit_name: 'Chiếc',
    estimate_date: '2025-03-15',
    quantity: 900,
    delivery_quantity: 450,
    delivery_process: 50,
    complete_date: '2025-03-15',
    is_packaged: true,
    deline_status: 'Đúng hạn',
    plan_quantity: 900,
    actual_quantity: 880,
    warehouse_import_quantity: 850,
    warehouse_import_wait_quantity: 30,
    iqc_ng_quantity: 0,
  },
  {
    customer_id: 'KH008',
    date: '2025-03-05',
    product_id: 'SP008',
    product_name: 'Sản phẩm H',
    unit_name: 'Bộ',
    estimate_date: '2025-03-16',
    quantity: 1100,
    delivery_quantity: 550,
    delivery_process: 50,
    complete_date: '',
    is_packaged: false,
    deline_status: 'Đang giao hàng',
    plan_quantity: 1100,
    actual_quantity: 1000,
    warehouse_import_quantity: 950,
    warehouse_import_wait_quantity: 50,
    iqc_ng_quantity: 4,
  },
  {
    customer_id: 'KH009',
    date: '2025-03-06',
    product_id: 'SP009',
    product_name: 'Sản phẩm I',
    unit_name: 'Cái',
    estimate_date: '2025-03-17',
    quantity: 1300,
    delivery_quantity: 1300,
    delivery_process: 100,
    complete_date: '2025-03-17',
    is_packaged: true,
    deline_status: 'Đúng hạn',
    plan_quantity: 1300,
    actual_quantity: 1300,
    warehouse_import_quantity: 1250,
    warehouse_import_wait_quantity: 50,
    iqc_ng_quantity: 6,
  },
  {
    customer_id: 'KH010',
    date: '2025-03-07',
    product_id: 'SP010',
    product_name: 'Sản phẩm J',
    unit_name: 'Chiếc',
    estimate_date: '2025-03-18',
    quantity: 700,
    delivery_quantity: 350,
    delivery_process: 50,
    complete_date: '2025-03-18',
    is_packaged: true,
    deline_status: 'Đúng hạn',
    plan_quantity: 700,
    actual_quantity: 680,
    warehouse_import_quantity: 660,
    warehouse_import_wait_quantity: 20,
    iqc_ng_quantity: 1,
  },
  {
    customer_id: 'KH006',
    date: '2025-03-03',
    product_id: 'SP006',
    product_name: 'Sản phẩm F',
    unit_name: 'Cái',
    estimate_date: '2025-03-12',
    quantity: 1200,
    delivery_quantity: 600,
    delivery_process: 50,
    complete_date: '2025-03-12',
    is_packaged: true,
    deline_status: 'Đúng hạn',
    plan_quantity: 1200,
    actual_quantity: 1150,
    warehouse_import_quantity: 1100,
    warehouse_import_wait_quantity: 50,
    iqc_ng_quantity: 3,
  },
  {
    customer_id: 'KH007',
    date: '2025-03-04',
    product_id: 'SP007',
    product_name: 'Sản phẩm G',
    unit_name: 'Chiếc',
    estimate_date: '2025-03-15',
    quantity: 900,
    delivery_quantity: 450,
    delivery_process: 50,
    complete_date: '2025-03-15',
    is_packaged: true,
    deline_status: 'Đúng hạn',
    plan_quantity: 900,
    actual_quantity: 880,
    warehouse_import_quantity: 850,
    warehouse_import_wait_quantity: 30,
    iqc_ng_quantity: 0,
  },
  {
    customer_id: 'KH008',
    date: '2025-03-05',
    product_id: 'SP008',
    product_name: 'Sản phẩm H',
    unit_name: 'Bộ',
    estimate_date: '2025-03-16',
    quantity: 1100,
    delivery_quantity: 550,
    delivery_process: 50,
    complete_date: '',
    is_packaged: false,
    deline_status: 'Đang giao hàng',
    plan_quantity: 1100,
    actual_quantity: 1000,
    warehouse_import_quantity: 950,
    warehouse_import_wait_quantity: 50,
    iqc_ng_quantity: 4,
  },
  {
    customer_id: 'KH009',
    date: '2025-03-06',
    product_id: 'SP009',
    product_name: 'Sản phẩm I',
    unit_name: 'Cái',
    estimate_date: '2025-03-17',
    quantity: 1300,
    delivery_quantity: 1300,
    delivery_process: 100,
    complete_date: '2025-03-17',
    is_packaged: true,
    deline_status: 'Đúng hạn',
    plan_quantity: 1300,
    actual_quantity: 1300,
    warehouse_import_quantity: 1250,
    warehouse_import_wait_quantity: 50,
    iqc_ng_quantity: 6,
  },
  {
    customer_id: 'KH010',
    date: '2025-03-07',
    product_id: 'SP010',
    product_name: 'Sản phẩm J',
    unit_name: 'Chiếc',
    estimate_date: '2025-03-18',
    quantity: 700,
    delivery_quantity: 350,
    delivery_process: 50,
    complete_date: '2025-03-18',
    is_packaged: true,
    deline_status: 'Đúng hạn',
    plan_quantity: 700,
    actual_quantity: 680,
    warehouse_import_quantity: 660,
    warehouse_import_wait_quantity: 20,
    iqc_ng_quantity: 1,
  },
  {
    customer_id: 'KH011',
    date: '2025-03-08',
    product_id: 'SP011',
    product_name: 'Sản phẩm K',
    unit_name: 'Bộ',
    estimate_date: '2025-03-19',
    quantity: 1600,
    delivery_quantity: 800,
    delivery_process: 50,
    complete_date: '',
    is_packaged: false,
    deline_status: 'Đang giao hàng',
    plan_quantity: 1600,
    actual_quantity: 1500,
    warehouse_import_quantity: 1450,
    warehouse_import_wait_quantity: 50,
    iqc_ng_quantity: 8,
  },
  {
    customer_id: 'KH012',
    date: '2025-03-09',
    product_id: 'SP012',
    product_name: 'Sản phẩm L',
    unit_name: 'Cái',
    estimate_date: '2025-03-20',
    quantity: 1400,
    delivery_quantity: 700,
    delivery_process: 50,
    complete_date: '2025-03-20',
    is_packaged: true,
    deline_status: 'Đúng hạn',
    plan_quantity: 1400,
    actual_quantity: 1400,
    warehouse_import_quantity: 1380,
    warehouse_import_wait_quantity: 20,
    iqc_ng_quantity: 2,
  },
  {
    customer_id: 'KH013',
    date: '2025-03-10',
    product_id: 'SP013',
    product_name: 'Sản phẩm M',
    unit_name: 'Chiếc',
    estimate_date: '2025-03-21',
    quantity: 1800,
    delivery_quantity: 900,
    delivery_process: 50,
    complete_date: '2025-03-21',
    is_packaged: true,
    deline_status: 'Đúng hạn',
    plan_quantity: 1800,
    actual_quantity: 1750,
    warehouse_import_quantity: 1700,
    warehouse_import_wait_quantity: 50,
    iqc_ng_quantity: 7,
  },
  {
    customer_id: 'KH014',
    date: '2025-03-11',
    product_id: 'SP014',
    product_name: 'Sản phẩm N',
    unit_name: 'Bộ',
    estimate_date: '2025-03-22',
    quantity: 1000,
    delivery_quantity: 600,
    delivery_process: 60,
    complete_date: '2025-03-22',
    is_packaged: true,
    deline_status: 'Đúng hạn',
    plan_quantity: 1000,
    actual_quantity: 950,
    warehouse_import_quantity: 940,
    warehouse_import_wait_quantity: 10,
    iqc_ng_quantity: 3,
  },
  {
    customer_id: 'KH015',
    date: '2025-03-12',
    product_id: 'SP015',
    product_name: 'Sản phẩm O',
    unit_name: 'Cái',
    estimate_date: '2025-03-23',
    quantity: 900,
    delivery_quantity: 400,
    delivery_process: 44.4,
    complete_date: '',
    is_packaged: false,
    deline_status: 'Đang giao hàng',
    plan_quantity: 900,
    actual_quantity: 850,
    warehouse_import_quantity: 800,
    warehouse_import_wait_quantity: 50,
    iqc_ng_quantity: 5,
  },
];
