import { BasicColumn } from '@/components/Table';

export function getBasicColumns(): BasicColumn[] {
  return [
    {
      title: 'BẢNG GHI CHÉP SỬA CHỮA BẢO DƯỠNG MÁY MÓC THIẾT BỊ',
      children: [
        {
          title: 'Ngày bảo dưỡng',
          dataIndex: 'maintenanceDate',
          align: 'center',
          width: 200,
        },
        {
          title: 'Tên thiết bị',
          dataIndex: 'equipmentName',
          align: 'center',
          width: 200,
        },
        {
          title: 'Đơn vị bảo dưỡng',
          dataIndex: 'maintenanceUnit',
          align: 'center',
          width: 200,
        },
        {
          title: 'Hạng mục bảo dưỡng',
          dataIndex: 'maintenanceCategory',
          align: 'center',
          width: 200,
        },
        {
          title: 'Nội dung bảo dưỡng thực tế',
          dataIndex: 'maintenanceContent',
          align: 'center',
          width: 200,
        },
        {
          title: 'Giải thích',
          dataIndex: 'explain',
          align: 'center',
          width: 200,
        },
      ],
    },
    {
      title: 'Phụ tùng linh kiện thay thế',
      dataIndex: 'phu_tung_thay_the',
      align: 'center',
      width: 200,
    },
    {
      title: 'Thời gian thực hiện (phút)',
      dataIndex: 'maintenanceTime',
      align: 'center',
      width: 180,
    },
    {
      title: 'Người thực hiện',
      dataIndex: 'maintenanceUser',
      align: 'center',
      width: 200,
    },
  ];
}

export function mockData(): any[] {
  return [
    {
      stt: 1,
      ngay_bao_duong: '13/09/2024',
      ten_thiet_bi: 'Máy 02',
      don_vi_bao_duong: 'Unit A',
      hang_muc_bao_duong: 'Type A',
      noi_dung_bao_duong: 'Note 1',
      giai_thich: '-',
      thoi_gian_thuc_hien: 60,
      nguoi_thuc_hien: 'Nguyen Van A',
    },
    {
      stt: 2,
      ngay_bao_duong: '13/09/2024',
      ten_thiet_bi: 'Máy 02',
      don_vi_bao_duong: 'Unit A',
      hang_muc_bao_duong: 'Type A',
      noi_dung_bao_duong: 'Note 1',
      giai_thich: '-',
      thoi_gian_thuc_hien: 60,
      nguoi_thuc_hien: 'Nguyen Van B',
    },
    {
      stt: 3,
      ngay_bao_duong: '13/09/2024',
      ten_thiet_bi: 'Máy 02',
      don_vi_bao_duong: 'Unit A',
      hang_muc_bao_duong: 'Type A',
      noi_dung_bao_duong: 'Note 1',
      giai_thich: '-',
      thoi_gian_thuc_hien: 60,
      nguoi_thuc_hien: 'Nguyen Van C',
    },
    {
      stt: 4,
      ngay_bao_duong: '13/09/2024',
      ten_thiet_bi: 'Máy 02',
      don_vi_bao_duong: 'Unit A',
      hang_muc_bao_duong: 'Type A',
      noi_dung_bao_duong: 'Note 1',
      giai_thich: '-',
      thoi_gian_thuc_hien: 60,
      nguoi_thuc_hien: 'Nguyen Van D',
    },
    {
      stt: 5,
      ngay_bao_duong: '13/09/2024',
      ten_thiet_bi: 'Máy 02',
      don_vi_bao_duong: 'Unit A',
      hang_muc_bao_duong: 'Type A',
      noi_dung_bao_duong: 'Note 1',
      giai_thich: '-',
      thoi_gian_thuc_hien: 60,
      nguoi_thuc_hien: 'Nguyen Van A',
    },
    {
      stt: 6,
      ngay_bao_duong: '13/09/2024',
      ten_thiet_bi: 'Máy 02',
      don_vi_bao_duong: 'Unit A',
      hang_muc_bao_duong: 'Type A',
      noi_dung_bao_duong: 'Note 1',
      giai_thich: '-',
      thoi_gian_thuc_hien: 60,
      nguoi_thuc_hien: 'Nguyen Van A',
    },
    {
      stt: 7,
      ngay_bao_duong: '13/09/2024',
      ten_thiet_bi: 'Máy 02',
      don_vi_bao_duong: 'Unit A',
      hang_muc_bao_duong: 'Type A',
      noi_dung_bao_duong: 'Note 1',
      giai_thich: '-',
      thoi_gian_thuc_hien: 60,
      nguoi_thuc_hien: 'Nguyen Van A',
    },
    {
      stt: 8,
      ngay_bao_duong: '13/09/2024',
      ten_thiet_bi: 'Máy 02',
      don_vi_bao_duong: 'Unit A',
      hang_muc_bao_duong: 'Type A',
      noi_dung_bao_duong: 'Note 1',
      giai_thich: '-',
      thoi_gian_thuc_hien: 60,
      nguoi_thuc_hien: 'Nguyen Van A',
    },
    {
      stt: 9,
      ngay_bao_duong: '13/09/2024',
      ten_thiet_bi: 'Máy 02',
      don_vi_bao_duong: 'Unit A',
      hang_muc_bao_duong: 'Type A',
      noi_dung_bao_duong: 'Note 1',
      giai_thich: '-',
      thoi_gian_thuc_hien: 60,
      nguoi_thuc_hien: 'Nguyen Van A',
    },
    {
      stt: 10,
      ngay_bao_duong: '13/09/2024',
      ten_thiet_bi: 'Máy 02',
      don_vi_bao_duong: 'Unit A',
      hang_muc_bao_duong: 'Type A',
      noi_dung_bao_duong: 'Note 1',
      giai_thich: '-',
      thoi_gian_thuc_hien: 60,
      nguoi_thuc_hien: 'Nguyen Van A',
    },
  ];
}
