import { BasicColumn } from '@/components/Table';
import { formatNumber } from '@/utils/helper/tsxHelper';

export function getBasicColumns(): BasicColumn[] {
  return [
    {
      title: 'Công đoạn',
      dataIndex: 'process_id',
      align: 'center',
      fixed: 'left',
      width: 100,
      customRender: ({ record }) => {
        return record?.equipment?.process_id || '-';
      },
    },
    {
      title: 'Máy',
      dataIndex: 'equipment_id',
      align: 'center',
      width: 200,
    },
    {
      title: 'Thời gian dừng',
      dataIndex: 'stop_time',
      align: 'center',
      width: 150,
    },
    {
      title: 'Thời gian chạy',
      dataIndex: 'start_time',
      align: 'center',
      width: 150,
    },
    {
      title: 'Tổng thời gian xử lý',
      align: 'center',
      width: 150,
      customRender: ({ record }) => {
        if (!record?.stop_time || !record?.start_time) return '-';
        const stopTime = new Date(record?.stop_time).getTime();
        const startTime = new Date(record?.start_time).getTime();
        const totalTime = Math.max(stopTime - startTime, startTime - stopTime);
        return totalTime > 0 ? `${formatNumber(totalTime / 1000 / 60)} phút` : 0;
      },
    },
    {
      title: 'Thời gian nhập lỗi',
      dataIndex: 'handle_time',
      align: 'center',
      width: 150,
    },
    {
      title: 'Mã lỗi',
      dataIndex: 'error_equipment_id',
      align: 'center',
      width: 100,
    },
    {
      title: 'Tên lỗi',
      align: 'center',
      width: 200,
      customRender: ({ record }) => {
        return record?.equipment_error?.error_equipment_name || '-';
      },
    },
    {
      title: 'Nguyên nhân',
      align: 'center',
      width: 200,
      customRender: ({ record }) => {
        return record?.equipment_error?.reason || '-';
      },
    },
    {
      title: 'Biện pháp khắc phục',
      dataIndex: 'fix',
      align: 'center',
      width: 300,
      customRender: ({ record }) => {
        return record?.equipment_error?.fix || '-';
      },
    },
    {
      title: 'Biện pháp phòng ngừa',
      dataIndex: 'protection_measures',
      align: 'center',
      width: 300,
      customRender: ({ record }) => {
        return record?.equipment_error?.protection_measures || '-';
      },
    },
    {
      title: 'Người xử lý',
      dataIndex: 'handler_name',
      align: 'center',
      width: 200,
      customRender: ({ record }) => {
        return record?.handler?.name || '-';
      },
    },
  ];
}

export function getActionColumn(): BasicColumn {
  return {
    width: 120,
    title: 'Thao tác',
    dataIndex: 'action',
  };
}

export function mockData(): any[] {
  return [
    {
      process_id: 'DG',
      equipment_name: 'LINE1',
      stop_time: '2024-09-26 10:00:00',
      start_time: '2024-09-26 10:30:00',
      total_time: '30m',
      handle_time: '2024-09-26 10:05:00',
      error_equipment_id: 'ERR-001',
      equipment_error_name: 'Lỗi động cơ',
      reason: 'Động cơ quá nhiệt',
      fix: 'Tắt máy và khởi động lại',
      protection_measures: 'Kiểm tra nhiệt độ động cơ định kỳ',
      handler_name: 'Nguyễn Văn A',
    },
    {
      process_id: 'BE',
      equipment_name: 'BE15',
      stop_time: '2024-09-26 11:00:00',
      start_time: '2024-09-26 11:45:00',
      total_time: '45m',
      handle_time: '2024-09-26 11:15:00',
      error_equipment_id: 'ERR-002',
      equipment_error_name: 'Lỗi trục chính',
      reason: 'Trục chính bị lệch',
      fix: 'Điều chỉnh trục và khởi động lại',
      protection_measures: 'Kiểm tra trục định kỳ trước khi vận hành',
      handler_name: 'Trần Văn B',
    },
    {
      process_id: 'BE',
      equipment_name: 'BE09',
      stop_time: '2024-09-26 09:00:00',
      start_time: '2024-09-26 09:20:00',
      total_time: '20m',
      handle_time: '2024-09-26 09:10:00',
      error_equipment_id: 'ERR-003',
      equipment_error_name: 'Lỗi điện',
      reason: 'Mất nguồn điện đột ngột',
      fix: 'Kiểm tra và cấp lại nguồn điện',
      protection_measures: 'Kiểm tra hệ thống điện thường xuyên',
      handler_name: 'Lê Văn C',
    },
    {
      process_id: 'BE',
      equipment_name: 'BE11',
      stop_time: '2024-09-26 12:00:00',
      start_time: '2024-09-26 12:35:00',
      total_time: '35m',
      handle_time: '2024-09-26 12:15:00',
      error_equipment_id: 'ERR-004',
      equipment_error_name: 'Lỗi hệ thống làm mát',
      reason: 'Hệ thống làm mát ngừng hoạt động',
      fix: 'Thay thế bộ làm mát',
      protection_measures: 'Bảo dưỡng hệ thống làm mát định kỳ',
      handler_name: 'Phạm Văn D',
    },
    {
      process_id: 'BE',
      equipment_name: 'BE10',
      stop_time: '2024-09-26 08:00:00',
      start_time: '2024-09-26 08:45:00',
      total_time: '45m',
      handle_time: '2024-09-26 08:30:00',
      error_equipment_id: 'ERR-005',
      equipment_error_name: 'Lỗi phần mềm',
      reason: 'Phần mềm bị treo',
      fix: 'Khởi động lại phần mềm',
      protection_measures: 'Cập nhật phần mềm thường xuyên',
      handler_name: 'Nguyễn Thị E',
    },
    {
      process_id: 'CP',
      equipment_name: 'CATPHAY04',
      stop_time: '2024-09-26 14:00:00',
      start_time: '2024-09-26 14:50:00',
      total_time: '50m',
      handle_time: '2024-09-26 14:20:00',
      error_equipment_id: 'ERR-006',
      equipment_error_name: 'Lỗi cơ khí',
      reason: 'Đai truyền bị hỏng',
      fix: 'Thay thế đai truyền',
      protection_measures: 'Kiểm tra định kỳ tình trạng đai truyền',
      handler_name: 'Võ Văn F',
    },
    {
      process_id: 'DG',
      equipment_name: 'LINE1',
      stop_time: '2024-09-26 10:00:00',
      start_time: '2024-09-26 10:30:00',
      total_time: '30m',
      handle_time: '2024-09-26 10:05:00',
      error_equipment_id: 'ERR-001',
      equipment_error_name: 'Lỗi động cơ',
      reason: 'Động cơ quá nhiệt',
      fix: 'Tắt máy và khởi động lại',
      protection_measures: 'Kiểm tra nhiệt độ động cơ định kỳ',
      handler_name: 'Nguyễn Văn A',
    },
    {
      process_id: 'BE',
      equipment_name: 'BE15',
      stop_time: '2024-09-26 11:00:00',
      start_time: '2024-09-26 11:45:00',
      total_time: '45m',
      handle_time: '2024-09-26 11:15:00',
      error_equipment_id: 'ERR-002',
      equipment_error_name: 'Lỗi trục chính',
      reason: 'Trục chính bị lệch',
      fix: 'Điều chỉnh trục và khởi động lại',
      protection_measures: 'Kiểm tra trục định kỳ trước khi vận hành',
      handler_name: 'Trần Văn B',
    },
    {
      process_id: 'BE',
      equipment_name: 'BE09',
      stop_time: '2024-09-26 09:00:00',
      start_time: '2024-09-26 09:20:00',
      total_time: '20m',
      handle_time: '2024-09-26 09:10:00',
      error_equipment_id: 'ERR-003',
      equipment_error_name: 'Lỗi điện',
      reason: 'Mất nguồn điện đột ngột',
      fix: 'Kiểm tra và cấp lại nguồn điện',
      protection_measures: 'Kiểm tra hệ thống điện thường xuyên',
      handler_name: 'Lê Văn C',
    },
    {
      process_id: 'BE',
      equipment_name: 'BE11',
      stop_time: '2024-09-26 12:00:00',
      start_time: '2024-09-26 12:35:00',
      total_time: '35m',
      handle_time: '2024-09-26 12:15:00',
      error_equipment_id: 'ERR-004',
      equipment_error_name: 'Lỗi hệ thống làm mát',
      reason: 'Hệ thống làm mát ngừng hoạt động',
      fix: 'Thay thế bộ làm mát',
      protection_measures: 'Bảo dưỡng hệ thống làm mát định kỳ',
      handler_name: 'Phạm Văn D',
    },
    {
      process_id: 'BE',
      equipment_name: 'BE10',
      stop_time: '2024-09-26 08:00:00',
      start_time: '2024-09-26 08:45:00',
      total_time: '45m',
      handle_time: '2024-09-26 08:30:00',
      error_equipment_id: 'ERR-005',
      equipment_error_name: 'Lỗi phần mềm',
      reason: 'Phần mềm bị treo',
      fix: 'Khởi động lại phần mềm',
      protection_measures: 'Cập nhật phần mềm thường xuyên',
      handler_name: 'Nguyễn Thị E',
    },
    {
      process_id: 'CP',
      equipment_name: 'CATPHAY04',
      stop_time: '2024-09-26 14:00:00',
      start_time: '2024-09-26 14:50:00',
      total_time: '50m',
      handle_time: '2024-09-26 14:20:00',
      error_equipment_id: 'ERR-006',
      equipment_error_name: 'Lỗi cơ khí',
      reason: 'Đai truyền bị hỏng',
      fix: 'Thay thế đai truyền',
      protection_measures: 'Kiểm tra định kỳ tình trạng đai truyền',
      handler_name: 'Võ Văn F',
    },
    {
      process_id: 'DG',
      equipment_name: 'LINE1',
      stop_time: '2024-09-26 10:00:00',
      start_time: '2024-09-26 10:30:00',
      total_time: '30m',
      handle_time: '2024-09-26 10:05:00',
      error_equipment_id: 'ERR-001',
      equipment_error_name: 'Lỗi động cơ',
      reason: 'Động cơ quá nhiệt',
      fix: 'Tắt máy và khởi động lại',
      protection_measures: 'Kiểm tra nhiệt độ động cơ định kỳ',
      handler_name: 'Nguyễn Văn A',
    },
    {
      process_id: 'CN',
      equipment_name: 'CN15',
      stop_time: '2024-09-26 11:00:00',
      start_time: '2024-09-26 11:45:00',
      total_time: '45m',
      handle_time: '2024-09-26 11:15:00',
      error_equipment_id: 'ERR-002',
      equipment_error_name: 'Lỗi trục chính',
      reason: 'Trục chính bị lệch',
      fix: 'Điều chỉnh trục và khởi động lại',
      protection_measures: 'Kiểm tra trục định kỳ trước khi vận hành',
      handler_name: 'Trần Văn B',
    },
    {
      process_id: 'CN',
      equipment_name: 'CN09',
      stop_time: '2024-09-26 09:00:00',
      start_time: '2024-09-26 09:20:00',
      total_time: '20m',
      handle_time: '2024-09-26 09:10:00',
      error_equipment_id: 'ERR-003',
      equipment_error_name: 'Lỗi điện',
      reason: 'Mất nguồn điện đột ngột',
      fix: 'Kiểm tra và cấp lại nguồn điện',
      protection_measures: 'Kiểm tra hệ thống điện thường xuyên',
      handler_name: 'Lê Văn C',
    },
    {
      process_id: 'CN',
      equipment_name: 'CN11',
      stop_time: '2024-09-26 12:00:00',
      start_time: '2024-09-26 12:35:00',
      total_time: '35m',
      handle_time: '2024-09-26 12:15:00',
      error_equipment_id: 'ERR-004',
      equipment_error_name: 'Lỗi hệ thống làm mát',
      reason: 'Hệ thống làm mát ngừng hoạt động',
      fix: 'Thay thế bộ làm mát',
      protection_measures: 'Bảo dưỡng hệ thống làm mát định kỳ',
      handler_name: 'Phạm Văn D',
    },
    {
      process_id: 'CN',
      equipment_name: 'CN10',
      stop_time: '2024-09-26 08:00:00',
      start_time: '2024-09-26 08:45:00',
      total_time: '45m',
      handle_time: '2024-09-26 08:30:00',
      error_equipment_id: 'ERR-005',
      equipment_error_name: 'Lỗi phần mềm',
      reason: 'Phần mềm bị treo',
      fix: 'Khởi động lại phần mềm',
      protection_measures: 'Cập nhật phần mềm thường xuyên',
      handler_name: 'Nguyễn Thị E',
    },
    {
      process_id: 'CP',
      equipment_name: 'CATPHAY04',
      stop_time: '2024-09-26 14:00:00',
      start_time: '2024-09-26 14:50:00',
      total_time: '50m',
      handle_time: '2024-09-26 14:20:00',
      error_equipment_id: 'ERR-006',
      equipment_error_name: 'Lỗi cơ khí',
      reason: 'Đai truyền bị hỏng',
      fix: 'Thay thế đai truyền',
      protection_measures: 'Kiểm tra định kỳ tình trạng đai truyền',
      handler_name: 'Võ Văn F',
    },
    {
      process_id: 'DG',
      equipment_name: 'LINE1',
      stop_time: '2024-09-26 10:00:00',
      start_time: '2024-09-26 10:30:00',
      total_time: '30m',
      handle_time: '2024-09-26 10:05:00',
      error_equipment_id: 'ERR-001',
      equipment_error_name: 'Lỗi động cơ',
      reason: 'Động cơ quá nhiệt',
      fix: 'Tắt máy và khởi động lại',
      protection_measures: 'Kiểm tra nhiệt độ động cơ định kỳ',
      handler_name: 'Nguyễn Văn A',
    },
    {
      process_id: 'CN',
      equipment_name: 'CN15',
      stop_time: '2024-09-26 11:00:00',
      start_time: '2024-09-26 11:45:00',
      total_time: '45m',
      handle_time: '2024-09-26 11:15:00',
      error_equipment_id: 'ERR-002',
      equipment_error_name: 'Lỗi trục chính',
      reason: 'Trục chính bị lệch',
      fix: 'Điều chỉnh trục và khởi động lại',
      protection_measures: 'Kiểm tra trục định kỳ trước khi vận hành',
      handler_name: 'Trần Văn B',
    },
    {
      process_id: 'CN',
      equipment_name: 'CN09',
      stop_time: '2024-09-26 09:00:00',
      start_time: '2024-09-26 09:20:00',
      total_time: '20m',
      handle_time: '2024-09-26 09:10:00',
      error_equipment_id: 'ERR-003',
      equipment_error_name: 'Lỗi điện',
      reason: 'Mất nguồn điện đột ngột',
      fix: 'Kiểm tra và cấp lại nguồn điện',
      protection_measures: 'Kiểm tra hệ thống điện thường xuyên',
      handler_name: 'Lê Văn C',
    },
    {
      process_id: 'CN',
      equipment_name: 'CN11',
      stop_time: '2024-09-26 12:00:00',
      start_time: '2024-09-26 12:35:00',
      total_time: '35m',
      handle_time: '2024-09-26 12:15:00',
      error_equipment_id: 'ERR-004',
      equipment_error_name: 'Lỗi hệ thống làm mát',
      reason: 'Hệ thống làm mát ngừng hoạt động',
      fix: 'Thay thế bộ làm mát',
      protection_measures: 'Bảo dưỡng hệ thống làm mát định kỳ',
      handler_name: 'Phạm Văn D',
    },
    {
      process_id: 'CN',
      equipment_name: 'CN10',
      stop_time: '2024-09-26 08:00:00',
      start_time: '2024-09-26 08:45:00',
      total_time: '45m',
      handle_time: '2024-09-26 08:30:00',
      error_equipment_id: 'ERR-005',
      equipment_error_name: 'Lỗi phần mềm',
      reason: 'Phần mềm bị treo',
      fix: 'Khởi động lại phần mềm',
      protection_measures: 'Cập nhật phần mềm thường xuyên',
      handler_name: 'Nguyễn Thị E',
    },
    {
      process_id: 'CP',
      equipment_name: 'CATPHAY04',
      stop_time: '2024-09-26 14:00:00',
      start_time: '2024-09-26 14:50:00',
      total_time: '50m',
      handle_time: '2024-09-26 14:20:00',
      error_equipment_id: 'ERR-006',
      equipment_error_name: 'Lỗi cơ khí',
      reason: 'Đai truyền bị hỏng',
      fix: 'Thay thế đai truyền',
      protection_measures: 'Kiểm tra định kỳ tình trạng đai truyền',
      handler_name: 'Võ Văn F',
    },
  ];
}
